# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7fddfb249b80061b61da7154a67aeb169ee1f99c7a39caca5c7d56b3c5ce432a9e9616ef2a5758aa65ad4ed0b5d0b4e9eb2ca94afef0865cb421d38f678bed60

test:
  secret_key_base: 5c0759873dae92beed16b9005950bc154a680085d36cb0b84094c6006cafde0df799b13c66ea3760a17106a085b3c433124b8f5aedc469236740033234b6c870

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
